/* 
 * This file is part of biomcmc-lib, a low-level library for phylogenomic analysis.
 * Copyright (C) 2019-today  Leonardo de Oliveira Martins [ leomrtns at gmail.com;  http://www.leomartins.org ]
 *
 * biomcmc is free software; you can redistribute it and/or modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be usefulull, but WITHOUT ANY WARRANTY; without even the implied 
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICullAR PURPOSE.  See the GNU General Public License for more 
 * details (file "COPYING" or http://www.gnu.org/copyleft/gpl.html).
 */

/*! \file fortune_cookies.c 
 *  \brief List of inspirational quotes from the linux package `fortune` 
 */

#include "fortune_cookies.h"

const char prt_col_reset[] = "\e[0m";
const char *prt_col[][8]={ // 0-black   1-red   2-grn   3-yel   4-blu   5-mag   6-cyn   7-white
   {"\e[0;30m",  "\e[0;31m",  "\e[0;32m",  "\e[0;33m",  "\e[0;34m",  "\e[0;35m",  "\e[0;36m",  "\e[0;37m"},  // 0 regular text
   {"\e[1;30m",  "\e[1;31m",  "\e[1;32m",  "\e[1;33m",  "\e[1;34m",  "\e[1;35m",  "\e[1;36m",  "\e[1;37m"},  // 1 regular bold text
   {"\e[4;30m",  "\e[4;31m",  "\e[4;32m",  "\e[4;33m",  "\e[4;34m",  "\e[4;35m",  "\e[4;36m",  "\e[4;37m"},  // 2 regular underline text
   {"\e[40m",    "\e[41m",    "\e[42m",    "\e[43m",    "\e[44m",    "\e[45m",    "\e[46m",    "\e[47m"},    // 3 regular background
   {"\e[0;100m", "\e[0;101m", "\e[0;102m", "\e[0;103m", "\e[0;104m", "\e[0;105m", "\e[0;106m", "\e[0;107m"}, // 4 high intensity underground
   {"\e[0;90m",  "\e[0;91m",  "\e[0;92m",  "\e[0;93m",  "\e[0;94m",  "\e[0;95m",  "\e[0;96m",  "\e[0;97m"},  // 5 high intensity text 
   {"\e[1;90m",  "\e[1;91m",  "\e[1;92m",  "\e[1;93m",  "\e[1;94m",  "\e[1;95m",  "\e[1;96m",  "\e[1;97m"}   // 6 bold high intensity text
};

// curiosity. to add quotes with gawk: gawk '{print q,$0,q,","}' q="\""
uint16_t biomcmc_fortune_cookies_size = 329;
char *biomcmc_fortune_cookies[] = {
  " The most secure code in the world is code which is never written. -- Colin Percival",
  " Becoming sufficiently familiar with something is a substitute for understanding it. -- John Conway",
  " Mathematics is the simple bit. Its the stuff we can understand. Its cats that are complicated.  -- John Conway",
  " Far better an approximate answer to the right question, which is often vague, than an exact answer to the wrong question, which can always be made precise. -- John Tukey",
  " A good programmer is someone who always looks both ways before crossing a one-way street. -- Doug Linder",
  " A bug in the code is worth two in the documentation",
  " A bug in the hand is better than one as yet undetected",
  " A complex system that works is invariably found to have evolved from a\n simple system that works",
  " A computer scientist is someone who fixes things that aren't broken",
  " A hacker does for love what others would not do for money",
  " A language that doesn't affect the way you think about programming is not worth knowing",
  " A language that doesn't have everything is actually easier to program in than some that do. -- Dennis M. Ritchie",
  " A large number of installed systems work by fiat.  That is, they work by being declared to work. -- Anatol Holt",
  " A list is only as strong as its weakest link. -- Don Knuth",
  " A successful [software] tool is one that was used to do something undreamed of by its author. -- S. C. Johnson",
  " All constants are variables.",
  " All the simple programs have been written.",
  " And on the seventh day, He exited from append mode.",
  " Another megabytes the dust.",
  " Any given program will expand to fill available memory.",
  " Any given program, when running, is obsolete.",
  " Any program which runs right is obsolete.",
  " Any programming language is at its best before it is implemented and used.",
  " As a computer, I find your faith in technology amusing.",
  " As far as we know, our computer has never had an undetected error. -- Weisert",
  " As of next Tuesday, C will be flushed in favor of COBOL. Please update your programs.",
  " As of next week, passwords will be entered in Morse code.",
  " As Will Rogers would have said, \"There is no such things as a free variable.\"",
  " ASCII a stupid question, you get an EBCDIC answer.",
  " ASHes to ASHes, DOS to DOS.",
  " At the source of every error which is blamed on the computer you will find at least two human errors, including the error of blaming it on the computer.",
  " BASIC is the Computer Science equivalent of `Scientific Creationism'.",
  " Beware of bugs in the above code; I have only proved it correct, not tried it. -- Donald Knuth",
  " Beware of Programmers who carry screwdrivers. -- Leonard Brandwein",
  " Computers are not intelligent.  They only think they are.",
  " Computers are unreliable, but humans are even more unreliable. Any system which depends on human reliability is unreliable. -- Gilb",
  " Computers are useless.  They can only give you answers.	-- Pablo Picasso",
  " Coding is easy;  All you do is sit staring at a terminal until the drops of blood form on your forehead.",
  " Disclaimer: These opinions are my own, though for a small fee they be yours too. -- Dave Haynie",
  " Disraeli was pretty close: actually, there are Lies, Damn lies, Statistics, Benchmarks, and Delivery dates.",
  " Don't sweat it -- it's only ones and zeros. -- P. Skelly",
  " E Pluribus Unix",
  " Happiness is twin floppies.",
  " Help me, I'm a prisoner in a Fortune cookie file!",
  " Heuristics are bug ridden by definition.  If they didn't have bugs, then they'd be algorithms.",
  " I came, I saw, I deleted all your files.",
  " I do not fear computers.  I fear the lack of them. -- Isaac Asimov",
  " I wish you humans would leave me alone.",
  " If a listener nods his head when you're explaining your program, wake him up.",
  " If a train station is a place where a train stops, what's a workstation?",
  " If at first you don't succeed, you must be a programmer.",
  " If it has syntax, it isn't user friendly.",
  " If it happens once, it's a bug.\nIf it happens twice, it's a feature.\nIf it happens more than twice, it's a design philosophy.",
  " If the code and the comments disagree, then both are probably wrong. -- Norm Schryer",
  " If you have a procedure with 10 parameters, you probably missed some.",
  " If this is timesharing, give me my share right now.",
  " Intel CPUs are not defective, they just act that way. -- Henry Spencer",
  " Is your job running?  You'd better go catch it!",
  " [It is] best to confuse only one issue at a time. -- K&R",
  " It's ten o'clock; do you know where your processes are?",
  " Let the machine do the dirty work. -- \"Elements of Programming Style\", Kernighan and Ritchie",
  " Life would be so much easier if we could just look at the source code. -- Dave Olson",
  " Long computations which yield zero are probably all for naught.",
  " May all your PUSHes be POPped.",
  " MSDOS is not dead, it just smells that way. -- Henry Spencer",
  " Much of the excitement we get out of our work is that we don't really know what we are doing.	-- E. Dijkstra",
  " Nearly every complex solution to a programming problem that I have looked at carefully has turned out to be wrong.	-- Brent Welch",
  " Never make anything simple and efficient when a way can be found to make it complex and wonderful.",
  " Never test for an error condition you don't know how to handle.	-- Steinbach",
  " On a clear disk you can seek forever. -- P. Denning",
  " One good reason why computers can do more work than people is that they never have to stop and answer the phone.",
  " Nobody said computers were going to be polite.",
  " Nobody's gonna believe that computers are intelligent until they start coming in late and lying about it.",
  " One person's error is another person's data.",
  " One picture is worth 128K words.",
  " Only great masters of style can succeed in being obtuse. -- Oscar Wilde\nMost UNIX programmers are great masters of style. -- The Unnamed Usenetter",
  " Over the shoulder supervision is more a need of the manager than the programming task.",
  " Premature optimization is the root of all evil. -- D. E. Knuth",
  " Profanity is the one language all programmers know best.",
  " Real computer scientists don't comment their code.  The identifiers are so long they can't afford the disk space.",
  " Real programmers don't comment their code.  It was hard to write, it should be hard to understand.",
  " Real programmers don't draw flowcharts. Flowcharts are, after all, the illiterate's form of documentation.  Cavemen drew flowcharts; look how much good it did them.",
  " Real Users find the one combination of bizarre input values that shuts down the system for days.",
  " Real Users never know what they want, but they always know when your program doesn't deliver it.",
  " Save yourself!  Reboot in 5 seconds!",
  " Say \"twenty-three-skiddoo\" to logout.",
  " She sells cshs by the cshore.",
  " Some people claim that the UNIX learning curve is steep, but at least you only have to climb it once.",
  " Staff meeting in the conference room in \%d minutes.",
  " The \"cutting edge\" is getting rather dull. -- Andy Purshottam",
  " The C Programming Language -- A language which combines the flexibility of assembly language with the power of assembly language.",
  " The programmer made me do it.",
  " The computing field is always in need of new cliches. -- Alan Perlis",
  " The difference between art and science is that science is what we understand well enough to explain to a computer.  Art is everything else.	-- Donald Knuth, 'Discover'",
  " The disks are getting full; purge a file today.",
  " The eleventh commandment was `Thou Shalt Compute' or `Thou Shalt Not Compute' -- I forget which.",
  " The less time planning, the more time programming.",
  " The meat is rotten, but the booze is holding out. Computer translation of 'The spirit is willing, but the flesh is weak.'",
  " The nice thing about standards is that there are so many of them to choose from. -- Andrew S. Tanenbaum",
  " The number of arguments is unimportant unless some of them are correct. -- Ralph Hartley",
  " The number of computer scientists in a room is inversely proportional to the number of bugs in their code.",
  " The number of UNIX installations has grown to 10, with more expected. -- The Unix Programmer's Manual, 2nd Edition, June 1972",
  " The world is coming to an end ... SAVE YOUR BUFFERS!!!",
  " The world is coming to an end.  Please log off.",
  " The world is not octal despite DEC.",
  " The trouble with computers is that they do what you tell them, not what you want.		-- D. Cohen",
  " The value of a program is proportional to the weight of its output.",
  " There are running jobs.  Why don't you go chase them?",
  " There are two ways to write error-free programs; only the third one works.",
  " This login session: $13.76, but for you $11.88.",
  " This process can check if this value is zero, and if it is, it does something child-like.		-- Forbes Burkowski, CS 454, University of Washington",
  " This screen intentionally left blank.",
  " Those who can't write, write manuals.",
  " Those who do not understand Unix are condemned to reinvent it, poorly. -- Henry Spencer",
  " This system will self-destruct in five minutes.",
  " After three days without programming, life becomes meaningless.	-- Geoffrey James, 'The Tao of Programming'",
  " Let the programmers be many and the managers few -- then all will	be productive. -- Geoffrey James, 'The Tao of Programming'",
  " Time for you to leave.	-- Geoffrey James, 'The Tao of Programming'",
  " Without the wind, the grass does not move.  Without software, hardware is useless.-- Geoffrey James, 'The Tao of Programming'",
  " To err is human -- to blame it on a computer is even more so.",
  " To err is human, to forgive, beyond the scope of the Operating System.",
  " To iterate is human, to recurse, divine. -- Robert Heller",
  " To the systems programmer, users and applications serve only to provide a test load.",
  " Truly simple systems... require infinite testing. -- Norman Augustine",
  " Trying to establish voice contact ... please yell into keyboard.",
  " Variables don't; constants aren't.",
  " We are experiencing system trouble -- do not adjust your terminal.",
  " We are Microsoft.  Unix is irrelevant.  Openness is futile.  Prepare to be assimilated.",
  " We don't really understand it, so we'll give it to the programmers.",
  " Whom computers would destroy, they must first drive mad.",
  " Within a computer, natural language is unnatural.",
  " You are an insult to my intelligence!  I demand that you log off immediately.",
  " You are lost in the Swamps of Despair.",
  " You can tune a piano, but you can't tuna fish.\nYou can tune a filesystem, but you can't tuna fish.\n-- from the tunefs(8) man page",
  " You can't go home again, unless you set \\$HOME.",
  " You can't make a program without broken egos.",
  " You don't have to know how the computer works, just how to work the computer.",
  " You had mail, but the super-user read it, and deleted it!",
  " You had mail. Paul read it, so ask him what it said.",
  " You have a tendency to feel you are superior to most computers.",
  " You have junk mail.",
  " Life is NP-hard, and then you die. -- Dave Cock",
  " Try to remove the color-problem by restarting your computer several times. -- Microsoft Internet Explorer's README.TXT",
  " You're not Dave.  Who are you?",
  " You're using a keyboard!  How quaint!",
  " Tell the programmers that their code should be more efficient!",
  " Your password is pitifully obvious.",
  " We have a policy that we are not being hacked. -- Lisa Kopp, Friendster rep, commenting on a security flaw",
  " You might have mail.",
  " You can't just ask customers what they want and then try to give that to them. By the time you get it built, they'll want something new. -- Steve Jobs (1955-2011)",
  " UNIX is very simple, it just needs a genius to understand its simplicity. -- Dennis Ritchie (1941-2011)",
  " C is quirky, flawed, and an enormous success. -- Dennis Ritchie (1941-2011)",
  " When I read commentary about suggestions for where C should go, I often think back and give thanks that it wasn't developed under the advice of a worldwide crowd. -- Dennis Ritchie (1941-2011)",
  " Mathematics is made of 50 percent formulas, 50 percent proofs, and 50 percent imagination. ",
  " A mathematician is a device for turning coffee into theorems (-- P. Erdos)\nAddendum: American coffee is good for lemmas.",
  " An engineer thinks that his equations are an approximation to reality. A physicist thinks reality is an approximation to his equations. A mathematician doesn't care. ",
  " Old mathematicians never die; they just lose some of their functions. ",
  " Mathematics is the art of giving the same name to different things. -- J. H. Poincare",
  " There is no logical foundation of mathematics, and Gödel has proved it! ",
  " Classification of mathematical problems as linear and nonlinear is like classification of the Universe as bananas and non-bananas. ",
  " Why was six afraid of seven? Because 7 8 9.",
  " What did one math book say to the other? Don\'t bother me I\'ve got my own problems!",
  " Don\'t anthropomorphize computers, they don\'t like it.",
  " Three statisticians went duck hunting. A duck was approaching and the first statistician shot, And missed the duck by being a foot too high. The secondshot and was a foot too low. The third cried, \"We hit it!\"",
  " Two is the oddest prime of all, because it\'s the only one that\'s even!",
  " Several scientists were asked to prove that all odd integers higher than 2 are prime.\n Mathematician: 3 is a prime, 5 is a prime, 7 is a prime, and by induction - every odd integer higher than 2 is a prime.\n Physicist: 3 is a prime, 5 is a prime, 7 is a prime, 9 is an experimental error, 11 is a prime. Just to be sure, try several randomly chosen numbers: 17 is a prime, 23 is a prime...\n Engineer: 3 is a prime, 5 is a prime, 7 is a prime, 9 is an approximation to a prime, 11 is a prime,...\n Programmer (reading the output on the screen): 3 is a prime, 3 is a prime, 3 a is prime, 3 is a prime....\n Biologist: 3 is a prime, 5 is a prime, 7 is a prime, 9 -- results have not arrived yet,...\n ",
  " This is a one line proof...if we start sufficiently far to the left.",
  " The problems for the exam will be similar to the discussed in the class. Of course, the numbers will be different. But not all of them. Pi will still be 3.14159...",
  " Proof by forward reference: Reference is usually to a forthcoming paper of the author, which is often not as forthcoming as at first.",
  " Proof by funding: How could three different government agencies be wrong?",
  " Mathematical definition of TRIVIAL:If I have to show you how to do this, you're in the wrong class.",
  " Mathematical definition of SKETCH OF A PROOF:I couldn\'t verify all the details, so I\'ll break it down into the parts I couldn\'t prove.",
  " Mathematical definition of CANONICAL FORM:4 out of 5 mathematicians surveyed recommended this as the final form for their students who choose to finish.",
  " Mathematical definition of TWO LINE PROOF:I\'ll leave out everything but the conclusion, you can\'t question \'em if you can\'t see \'em.",
  " Mathematical definition of BRIEFLY:I\'m running out of time, so I\'ll just write and talk faster.",
  " Mathematical definition of LET'S TALK THROUGH IT:I don\'t want to write it on the board lest I make a mistake.",
  " The highest moments in the life of a mathematician are the first few moments after one has proved the result, but before one finds the mistake. ",
  " The highest moments in the life of a programmer are the first few moments after one has compiled the code, but before one finds the bug. ",
  " Relations between pure and applied mathematicians are based on trust and understanding. Namely, pure mathematicians do not trust applied mathematicians, and applied mathematicians do not understand pure mathematicians. ",
  " If I have not seen as far as others, it is because giants were standing on my shoulders. (-- Hal Abelson)",
  " Mathematicians stand on each other\'s shoulders (-- Gauss). Mathematicians stand on each other\'s shoulders while computer scientists stand on each other\'s toes. (-- Richard Hamming)",
  " Q: Why do Computer Scientists get Halloween and Christmas mixed up?A: Because Oct. 31 = Dec. 25.",
  " Q:What is a dilemma? A: A lemma that proves two results.\n" ,
  " A budget is just a method of worrying before you spend money, as well as afterward.",
  " A committee is a group that keeps the minutes and loses hours. -- Milton Berle",
  " A committee is a life form with six or more legs and no brain. -- Lazarus Long, \"Time Enough For Love\"",
  " A committee takes root and grows, it flowers, wilts and dies, scattering the seed from which other committees will bloom. -- Parkinson",
  " A company is known by the men it keeps.",
  " A consultant is a person who borrows your watch, tells you what time it is, pockets the watch, and sends you a bill for it.",
  " A continuing flow of paper is sufficient to continue the flow of paper. -- Dyer",
  " A verbal contract isn't worth the paper it's written on. -- Samuel Goldwyn",
  " About the time we think we can make ends meet, somebody moves the ends. -- Herbert Hoover",
  " After all is said and done, a hell of a lot more is said than done.",
  " All I ask is a chance to prove that money can't make me happy.",
  " At these prices, I lose money -- but I make it up in volume. -- Peter G. Alaquon",
  " By working faithfully eight hours a day, you may eventually get to be boss and work twelve. -- Robert Frost",
  " Exceptions prove the rule, and wreck the budget. -- Miller",
  " Executive ability is deciding quickly and getting somebody else to do the work. -- John G. Pollard",
  " Good day to avoid cops. Crawl to work.",
  " Honesty pays, but it doesn't seem to pay enough to suit some people. -- F. M. Hubbard",
  " Hotels are tired of getting ripped off.  I checked into a hotel and they had towels from my house. -- Mark Guido",
  " How come everyone's going so slow if it's called rush hour?",
  " - How many people work here? \n - Oh, about half.",
  " I don't want to achieve immortality through my work.  I want to achieve immortality through not dying. -- Woody Allen",
  " I've got all the money I'll ever need if I die by 4 o'clock. -- Henny Youngman",
  " If all else fails, lower your standards.",
  " If I want your opinion, I'll ask you to fill out the necessary form.",
  " If you can't get your work done in the first 24 hours, work nights.",
  " If you can't learn to do it well, learn to enjoy doing it badly.",
  " If you don't have time to do it right, where are you going to find the time to do it over?",
  " Keep up the good work!  But please don't ask me to help.",
  " Living on Earth may be expensive, but it includes an annual free trip around the Sun.",
  " Remember -- only 10\% of anything can be in the top 10\%.",
  " The trouble with being punctual is that nobody's there to appreciate it. -- Franklin P. Jones",
  " The trouble with being punctual is that people think you have nothing more important to do.",
  " The trouble with money is it costs too much!",
  " There's nothing worse for your business than extra Santa Clauses smoking in the men's room. -- W. Bossert",
  " When your work speaks for itself, don't interrupt. -- Henry J. Kaiser",
  " When you don't know what to do, walk fast and look worried.",
  " Where there's a will, there's a relative.",
  " Where there's a will, there's an Inheritance Tax.",
  " We're living in a golden age.  All you need is gold. -- D. W. Robertson.",
  " This is Unix we\'re talking about, remember.  It\'s not supposed to be nice for the applications programmer.  -- Matthew Danish on debian-devel ",
  " ... but hey, this is Linux, isn\'t it meant to do infinite loops in 5 seconds?  -- Jonathan Oxer in the apt-cacher ChangeLog ",
  " A celebrity is a person who is known for his well-knownness. ",
  " A critic is a bundle of biases held loosely together by a sense of taste.  -- Whitney Balliett ",
  " A drama critic is a person who surprises a playwright by informing him what he meant. ",
  " A fool-proof method for sculpting an elephant: first, get a huge block of marble; then you chip away everything that doesn't look like an elephant. ",
  " A team effort is a lot of people doing what I say.  -- Michael Winner, British film director ",
  " Being a mime means never having to say you're sorry. ",
  " Hummingbirds never remember the words to songs. ",
  " I am a deeply superficial person.  -- Andy Warhol ",
  " If life is a stage, I want some better lighting. ",
  " It's all right letting yourself go as long as you can let yourself back.  -- Mick Jagger ",
  " It's difficult to see the picture when you are inside the frame. ",
  " It's not easy, being green.  -- Kermit the Frog ",
  " Satire is tragedy plus time.  -- Lenny Bruce ",
  " Spare no expense to save money on this one.  -- Samuel Goldwyn ",
  " That's no moon...  -- Obi-wan Kenobi ",
  " The best definition of a gentleman is a man who can play the accordion -- but doesn't. ",
  " There's nothing remarkable about it.  All one has to do is hit the right keys at the right time and the instrument plays itself.  -- J. S. Bach ",
  " There are things that are so serious that you can only joke about them  -- Heisenberg ",
  " Prediction is very difficult, especially of the future.  -- Niels Bohr ",
  " All my life I wanted to be someone; I guess I should have been more specific.  -- Jane Wagner ",
  " Do not underestimate the value of print statements for debugging. Don't have aesthetic convulsions when using them, either. ",
  " The last thing one knows in constructing a work is what to put first.  -- Blaise Pascal ",
  " A person with one watch knows what time it is; a person with two watches is never sure.   Proverb ",
  " For every problem there is one solution which is simple, neat, and wrong.  -- H. L. Mencken ",
  " You can't have everything... where would you put it?  -- Steven Wright ",
  " I was playing poker the other night... with Tarot cards. I got a full house and 4 people died.  -- Steven Wright ",
  " In the realm of scientific observation, luck is granted only to those who are prepared.  -- Louis Pasteur ",
  " Harrison's Postulate:  For every action, there is an equal and opposite criticism. ",
  " Doubt is not a pleasant condition, but certainty is absurd.  -- Voltaire ",
  " Imitation is the sincerest form of plagiarism. ",
  " As long as we're going to reinvent the wheel again, we might as well try making it round this time.  -- Mike Dennison ",
  " Everyone has a purpose in life.  Perhaps yours is watching television.  -- David Letterman ",
  " A fanatic is a person who can't change his mind and won't change the subject.  -- Winston Churchill ",
  " There is nothing new under the sun, but there are lots of old things  we don't know yet.  -- Ambrose Bierce ",
  " In space, no one can hear you fart. ",
  " Parkinson's Law:  Work expands to fill the time alloted it. ",
  " Karl's version of Parkinson's Law:  Work expands to exceed the time alloted it. ",
  " How to make a million dollars:  First, get a million dollars.  -- Steve Martin ",
  " Our business is run on trust.  We trust you will pay in advance. ",
  " Lead me not into temptation... I can find it myself. ",
  " Tell the truth and run.  -- Yugoslav proverb ",
  " It is easier to fight for principles than to live up to them.  -- Alfred Adler ",
  " If at first you don't succeed, you are running about average. ",
  " The trouble with doing something right the first time is that nobody appreciates how difficult it was.  -- Walt West ",
  " It's great to be smart 'cause then you know stuff. ",
  " May the forces of evil become confused on the way to your house.  -- George Carlin ",
  " Pohl's law:   Nothing is so good that somebody, somewhere, will not hate it. ",
  " Pray to God, but keep rowing to shore.  -- Russian Proverb ",
  " No problem is so formidable that you can't walk away from it.  -- C. Schulz ",
  " The voters have spoken, the bastards... ",
  " Buy land.  They've stopped making it.  -- Mark Twain ",
  " backups: always in season, never out of style. ",
  " Aren't you glad you're not getting all the government you pay for now? ",
  " I never let my schooling get in the way of my education.  -- Mark Twain ",
  " Professional wrestling:  ballet for the common man. ",
  " An idealist is one who, on noticing that a rose smells better than a cabbage, concludes that it will also make better soup. - H. L. Mencken ",
  " Heisenberg might have been here. ",
  " Money is the root of all money. ",
  " If you don't want your dog to have bad breath, do what I do:  Pour a little  Lavoris in the toilet.  -- Jay Leno ",
  " Here's something to think about:  How come you never see a headline like  \"Psychic Wins Lottery\"?  -- Jay Leno ",
  " Our vision is to speed up time, eventually eliminating it. -- Alex Schure ",
  " To err is human, to moo bovine.", 
  " This software's documentation contains the answer to every problem. Except yours.",
  " Don't take it personally, you dum-dum.",
  " Any given program, when running, is obsolete. " ,
  " Any given program costs more and takes longer each time it is run. " ,
  " If a program is useful, it will have to be changed. " ,
  " If a program is useless, it will have to be documented. " ,
  " Any given program will expand to fill all the available memory. " ,
  " The value of a program is inversely proportional to the weight of its output. " ,
  " Program complexity grows until it exceeds the capability of the programmer who must maintain it. " ,
  " Every non trivial program has at least one bug. \n Corollary 1 - A sufficient condition for program triviality is that " ,
  " it have no bugs.\n Corollary 2 - At least one bug will be observed after the author leaves the organization. " ,
  " Bugs will appear in one part of a working program when another 'unrelated' part is modified. " ,
  " The subtlest bugs cause the greatest damage and problems.\n Corollary - A subtle bug will modify storage thereby masquerading as some other problem. " ,
  " A 'debugged' program that crashes will wipe out source files on storage devices when there is the least available backup. " ,
  " A hardware failure will cause system software to crash, and the customer engineer will blame the programmer.\nA system software crash will cause hardware to act strangely and the programmers will blame the customer engineer. " ,
  " Undetectable errors are infinite in variety, in contrast to detectable errors, which by definition are limited. " ,
  " Adding manpower to a late software project makes it later. " ,
  " The documented interfaces between standard software modules will have undocumented quirks. " ,
  " The probability of a hardware failure disappearing is inversely proportional to the distance between the computer and the customer engineer. " ,
  " A working program is one that has only unobserved bugs. " ,
  " No matter how many resources you have, it is never enough. " ,
  " Any cool program always requires more memory than you have. When you finally buy enough memory, you will not have enough disk space. " ,
  " Disks are always full. It is futile to try to get more disk space. Data expands to fill any void. " ,
  " If a program actually fits in memory and has enough disk space, it is guaranteed to crash. " ,
  " If such a program has not crashed yet, it is waiting for a critical moment before it crashes. " ,
  " All components become obsolete. The speed with which components become obsolete is directly proportional to the price of the component. " ,
  " Software bugs are impossible to detect by anybody except the end user. " ,
  " The maintenance engineer will never have seen a model quite like yours before. " ,
  " It is axiomatic that any spares required will have just been discontinued and will be no longer in stock. " ,
  " If a circuit requires n components, then there will be only n - 1 components in locally-held stocks. " ,
  " A failure in a device will never appear until it has passed final inspection. " ,
  " A program generator creates programs that are more buggy than the program generator. " ,
  " No matter how hard you work, the boss will only appear when you access the Internet. " ,
  " The hard drive on your computer will only crash when it contains vital information that has not been backed up. " ,
  " All Constants are Variables. " ,
  " Any problem, no matter how complex, can be found by simple inspection.\nCorollary: A nagging intruder with unsought advice will spot it immediately. " ,
  " This software has five bugs, and this number doesn't depend on how many bugs have already been found.  " ,
  " An expert is someone brought in at the last minute to share the blame. " ,
  " Debugging is at least twice as hard as writing the program in the first place. So if your code is as clever as you can possibly make it, then by definition you're not smart enough to debug it. " ,
  " A patch is a piece of software which replaces old bugs with new bugs. " ,
  " The chances of a program doing what it's supposed to do is inversely proportional to the number of lines of code used to write it. " ,
  " Proof-read all e-mails three or four times before sending it. All errors are detected immediatly after being sent. " ,
  " Weekend, where are you?"
}; 

uint16_t biomcmc_fortune_bofh_size = 372; 
char *biomcmc_fortune_bofh[] = {
  " solar flares",
  " electromagnetic radiation from satellite debris",
  " static from nylon underwear",
  " static from plastic slide rules",
  " global warming",
  " poor power conditioning",
  " doppler effect",
  " hardware stress fractures",
  " magnetic interference from money/credit cards",
  " dry joints on cable plug",
  " we're waiting for [the phone company] to fix that line",
  " sounds like a Windows problem, try calling Microsoft support",
  " temporary routing anomaly",
  " somebody was calculating pi on the server",
  " fat electrons in the lines",
  " monitor resolution too high",
  " improperly oriented keyboard",
  " network packets travelling uphill (use a carrier pigeon)",
  " first Saturday after first full moon in Winter",
  " positron router malfunction",
  " cellular telephone interference (next time please answer your phone)",
  " techtonic stress",
  " (l)user error",
  " working as designed (feature not a bug). These programmers don't make mistakes.",
  " heavy gravity fluctuation, move computer to floor rapidly",
  " your boss plugged hairdryer into UPS",
  " not enough memory, go get system upgrade",
  " interrupt configuration error",
  " spaghetti cable cause packet failure",
  " boss forgot system password",
  " bank holiday - system operating credits not recharged",
  " virus attack, luser responsible",
  " waste water tank overflowed onto computer",
  " Complete Transient Lockout",
  " bad ether in the cables",
  " Change in Earth's rotational speed",
  " Cosmic ray particles crashed through the hard disk platter",
  " Smell from unhygienic staff wrecked the tape heads",
  " Little hamster in running wheel had coronary; waiting for replacement to be Fedexed from Wyoming",
  " Evil dogs hypnotised the night shift",
  " Plumber mistook routing panel for decorative wall fixture",
  " Electricians made popcorn in the power supply",
  " Groundskeepers stole the root password",
  " failed trials, system needs redesigned",
  " system has been recalled",
  " not approved by the FCC",
  " need to wrap system in aluminum foil to fix problem",
  " not properly grounded, please bury computer",
  " CPU needs recalibration",
  " bit bucket overflow",
  " descramble code needed from software company",
  " only available on a need to know basis",
  " knot in cables caused data stream to become twisted and kinked",
  " nesting roaches shorted out the ether cable",
  " The file system is full of it",
  " Daemons did it",
  " You're out of memory",
  " Typo in the code",
  " That's a great computer you have there; have you considered how it would work as a BSD machine?",
  " Please excuse me, I have to circuit an AC line through my head to get this database working.",
  " Support staff hung over, send aspirin and come back LATER.",
  " Someone is standing on the ethernet cable, causing a kink in the cable",
  " Windows 95 undocumented \"feature\"",
  " Runt packets",
  " Password is too complex to decrypt",
  " Electromagnetic energy loss",
  " Budget cuts",
  " Mouse chewed through power cable",
  " Stale file handle (next time use Tupperware(tm)!)",
  " Internet outage",
  " microbes too close to the computer",
  " Vendor no longer supports the product",
  " Small animal kamikaze attack on power supplies",
  " The vendor put the bug there.",
  " operators on strike due to broken coffee machine",
  " backup tape overwritten with copy of system manager's favourite CD",
  " UPS interrupted the server's power",
  " The electrician didn't know what the yellow cable was so he yanked the ethernet out.",
  " The keyboard isn't plugged in",
  " The air conditioning water supply pipe ruptured over the machine room",
  " The electricity substation in the car park blew up.",
  " The rolling stones concert down the road caused a brown out",
  " The salesman drove over the CPU board.",
  " The monitor is plugged into the serial port",
  " Root nameservers are out of sync",
  " your keyboard's space bar is generating spurious keycodes.",
  " the real ttys became pseudo ttys and vice-versa.",
  " the printer thinks its a router.",
  " the router thinks its a printer.",
  " we just switched to FDDI.",
  " halon system went off and killed the operators.",
  " user to computer ratio too high.",
  " user to computer ration too low.",
  " Sticky bits on disk.",
  " Power Company having EMP problems with their reactor",
  " new management; you need to look busy",
  " not enough forms filled before using this software",
  " It's not plugged in.",
  " because of network lag due to too many people playing deathmatch",
  " You put the disk in upside down.",
  " Daemons loose in system.",
  " BNC (brain not connected)",
  " UBNC (user brain not connected)",
  " disks spinning backwards - toggle the hemisphere jumper.",
  " new guy cross-connected phone lines with ac power bus.",
  " had to use hammer to free stuck disk drive heads.",
  " Too few computrons available.",
  " Flat tire on station wagon with tapes.  (\"Never underestimate the bandwidth of a station wagon full of tapes hurling down the highway\" Andrew S. Tannenbaum) ",
  " Communications satellite used by the military for star wars.",
  " Party-bug in the Aloha protocol.",
  " Insert coin for new game",
  " Someone needed the powerstrip, so they pulled the switch plug.",
  " My pony-tail hit the on/off switch on the power strip.",
  " Dumb terminal",
  " Zombie processes haunting the computer",
  " Incorrect time synchronization",
  " Stubborn processes",
  " non-redundant fan failure ",
  " monitor VLF leakage",
  " bugs in the RAID",
  " no \"any\" key on keyboard",
  " root rot",
  " Backbone Scoliosis",
  " /pub/lunch",
  " excessive collisions & not enough packet ambulances",
  " le0: no carrier: transceiver cable problem?",
  " pseudo-user on a pseudo-terminal",
  " Recursive traversal of loopback mount points",
  " Backbone adjustment",
  " OS swapped to disk",
  " vapors from evaporating sticky-note adhesives",
  " short leg on process table",
  " multicasts on broken packets",
  " ether leak",
  " Atilla the Hub",
  " endothermal recalibration",
  " loop found in loop in redundant loopback",
  " system consumed all the paper for paging",
  " Reformatting Page. Wait...",
  " ..disk or the processor is on fire.",
  " SCSI's too wide.",
  " runaway cat on system.",
  " Did you pay the new Support Fee?",
  " We only support a 1200 bps connection.",
  " Post-it Note Sludge leaked into the monitor.",
  " the curls in your keyboard cord are losing electricity.",
  " The monitor needs another box of pixels.",
  " kernel panic: write-only-memory (/dev/wom0) capacity exceeded.",
  " Write-only-memory subsystem too slow for this machine. Contact your local dealer.",
  " Quantum dynamics are affecting the transistors",
  " Police are examining all internet packets in the search for a narco-net-trafficker",
  " We are currently trying a new concept of using a live mouse.  Unfortunately, one has yet to survive being hooked up to the computer.....please bear with us.",
  " Only people with names beginning with 'A' are getting mail this week (a la Microsoft)",
  " We didn't pay the Internet bill and it's been cut off.",
  " Of course it doesn't work. We've performed a software upgrade.",
  " Change your language to Finnish.",
  " Fluorescent lights are generating negative ions. If turning them off doesn't work, take them out and put tin foil on the ends.",
  " High nuclear activity in your area.",
  " What office are you in? Oh, that one.  Did you know that your building was built over the universities first nuclear research site? And wow, aren't you the lucky one, your office is right over where the core is buried!",
  " The UPS doesn't have a battery backup.",
  " Recursivity.  Call back if it happens again.",
  " Someone thought The Big Red Button was a light switch.",
  " The mainframe needs to rest.  It's getting old, you know.",
  " I'm not sure.  Try calling the Internet's head office -- it's in the book.",
  " The lines are all busy (busied out, that is -- why let them in to begin with?).",
  " A star wars satellite accidently blew up the WAN.",
  " Fatal error right in front of screen",
  " That function is not currently supported, but Bill Gates assures us it will be featured in the next upgrade.",
  " wrong polarity of neutron flow",
  " replace the equipment sitting in front of the screen",
  " We had to turn off that service to comply with the CDA Bill.",
  " Someone is broadcasting pygmy packets and the router doesn't know how to deal with them.",
  " Fanout dropping voltage too much, try cutting some of those little traces",
  " Plate voltage too low on demodulator tube",
  " Too many little pins on CPU confusing it, bend back and forth until 10-20\% are neatly removed. Do _not_ leave metal bits visible!",
  " Software uses US measurements, but the OS is in metric...",
  " The computer fleetly, mouse and all.",
  " Your cat tried to eat the mouse.",
  " The Borg tried to assimilate your system. Resistance is futile.",
  " It must have been the lightning storm we had (yesterday) (last week) (last month)",
  " Due to Federal Budget problems we have been forced to cut back on the number of users able to access the system at one time. (namely none allowed....)",
  " Unfortunately we have run out of bits/bytes/whatever. Don't worry, the next supply will be coming next week.",
  " Program load too heavy for processor to lift.",
  " Processes running slowly due to weak power supply",
  " Our ISP is having {switching,routing,SMDS,frame relay} problems",
  " We've run out of licenses",
  " Interference from lunar radiation",
  " Standing room only on the bus.",
  " You need to install an RTFM interface.",
  " That would be because the software doesn't work.",
  " That's easy to fix, but I can't be bothered.",
  " Someone's tie is caught in the printer, and if anything else gets printed, he'll be in it too.",
  " We're upgrading /dev/null",
  " The Usenet news is out of date",
  " Our POP server was kidnapped by a weasel.",
  " It's stuck in the Web.",
  " Your modem doesn't speak English.",
  " The mouse escaped.",
  " All of the packets are empty.",
  " The UPS is on strike.",
  " Neutrino overload on the nameserver",
  " Melting hard drives",
  " Someone has messed up the kernel pointers",
  " The kernel license has expired",
  " Netscape has crashed",
  " The cord jumped over and hit the power switch.",
  " It was OK before you touched it.",
  " Bit rot",
  " U.S. Postal Service",
  " Your Flux Capacitor has gone bad.",
  " The static electricity routing is acting up...",
  " Traceroute says that there is a routing problem in the backbone.  It's not our problem.",
  " The co-locator cannot verify the frame-relay gateway to the ISDN server.",
  " High altitude condensation from U.S.A.F prototype aircraft has contaminated the primary subnet mask. Turn off your computer for 9 days to avoid damaging it.",
  " Lawn mower blade in your fan need sharpening",
  " Electrons on a bender",
  " Telecommunications is downgrading.",
  " Hard drive sleeping. Let it wake up on it's own...",
  " Interference between the keyboard and the chair.",
  " The CPU has shifted, and become decentralized.",
  " Due to the CDA, we no longer have a root account.",
  " We ran out of dial tone and we're and waiting for the phone company to deliver another bottle.",
  " You must've hit the wrong any key.",
  " Too many interrupts",
  " Not enough interrupts",
  " The data on your hard drive is out of balance. Start taking yoga classes.",
  " Digital Manipulator exceeding velocity parameters",
  " appears to be a Slow/Narrow SCSI-0 Interface problem",
  " microelectronic Riemannian curved-space fault in write-only file system",
  " routing problems on the neural net",
  " IRQ-problems with the Un-Interruptible-Power-Supply",
  " CPU-angle has to be adjusted because of vibrations coming from the nearby road",
  " CD-ROM server needs recalibration",
  " incompatible bit-registration operators",
  " your process is not ISO 9000 compliant",
  " Internet exceeded Luser level, please wait until a luser logs off before attempting to log back on.",
  " Your computer hasn't been returning all the bits it gets from the Internet.",
  " Your processor has processed too many instructions.  Turn it off immediately, do not type any commands!!",
  " Your packets were eaten by the terminator",
  " Your processor does not develop enough heat. Leave the computer in the Sun for a few hours.",
  " We need a licensed electrician to replace the light bulbs in the computer room.",
  " Server depressed, needs Prozac",
  " those damn raccoons!",
  " suboptimal routing experience",
  " A plumber is needed, the network drain is clogged",
  " 50\% of the manual is in .pdf readme files",
  " the AA battery in the wallclock sends magnetic interference",
  " the xy axis in the trackball is coordinated with the summer solstice",
  " the butane lighter causes the pincushioning",
  " old inkjet cartridges emanate barium-based fumes",
  " manager in the cable duct",
  " HTTPD Error 666 : BOFH was here",
  " HTTPD Error 4004 : very old Intel cpu - insufficient processing power",
  " The ATM board has run out of 10 pound notes.  We are having a whip round to refill it, care to contribute ?",
  " Having to manually track the satellite.",
  " Your/our computer(s) had suffered a memory leak, and we are waiting for them to be topped up.",
  " The rubber band broke",
  " We're on Token Ring, and it looks like the token got loose.",
  " Stray Alpha Particles from memory packaging caused Hard Memory Error on Server.",
  " paradigm shift...without a clutch",
  " PEBKAC (Problem Exists Between Keyboard And Chair)",
  " The cables are not the same length.",
  " Second-system effect.",
  " Chewing gum on /dev/sd3c",
  " Boredom in the Kernel.",
  " I'd love to help you -- it's just that the Boss won't let me near the computer. ",
  " struck by the Good Times virus",
  " YOU HAVE AN I/O ERROR -> Incompetent Operator error",
  " Your parity check is overdrawn and you're out of cache.",
  " Sand fleas eating the Internet cables",
  " parallel processors running perpendicular today",
  " ATM cell has no roaming feature turned on, notebooks can't connect",
  " Webmasters kidnapped by evil cult.",
  " Failure to adjust for daylight savings time.",
  " Virus transmitted from computer to sysadmins.",
  " Virus due to computers having unsafe sex.",
  " Incorrectly configured static routes on the corerouters.",
  " Forced to support NT servers; sysadmins quit.",
  " Suspicious pointer corrupted virtual machine",
  " It's the InterNIC's fault.",
  " Root name servers corrupted. Try renaming all machines to obscure TV series characters. ",
  " Budget cuts forced us to sell all the power cords for the servers.",
  " Someone hooked the twisted pair wires into the answering machine.",
  " Operators killed by year 2000 bug bite.",
  " We've picked COBOL as the language of choice.",
  " Operators killed when huge stack of backup tapes fell over.",
  " Robotic tape changer mistook operator's tie for a backup tape.",
  " Someone was smoking in the computer room and set off the halon systems.",
  " The Internet is being scanned for viruses.",
  " Your computer's union contract is set to expire at midnight.",
  " Bad user karma.",
  " /dev/clue was linked to /dev/null",
  " Increased sunspot activity.",
  " We already sent around a notice about that.",
  " It's union rules. There's nothing we can do about it. Sorry.",
  " Interference from the Van Allen Belt.",
  " Jupiter is aligned with Mars.",
  " Redundant ACLs. ",
  " Mail server hit by UniSpammer.",
  " T-1's congested due to porn traffic to the news server.",
  " Data for intranet got routed through the extranet and landed on the internet.",
  " We are Microsoft.  What you are experiencing is not a bug; it is an undocumented feature.",
  " Sales staff sold a product we don't offer.",
  " Sysadmin didn't hear pager go off due to loud music from bar-room speakers.",
  " Sysadmin accidentally destroyed pager with a large hammer.",
  " Sysadmins unavailable because they are in a meeting talking about why they are unavailable so much.",
  " Bad cafeteria food landed all the sysadmins in the hospital.",
  " Route flapping at the NAP.",
  " Computers under water due to SYN flooding.",
  " The vulcan-death-grip ping has been applied.",
  " Electrical conduits in machine room are melting.",
  " Traffic jam on the Information Superhighway.",
  " Radial Telemetry Infiltration",
  " Cow-tippers tipped a cow onto the server.",
  " tachyon emissions overloading the system",
  " Maintenance window broken",
  " We're out of slots on the server",
  " Computer room being moved.  Our systems are down for the weekend.",
  " Sysadmins busy fighting SPAM.",
  " Repeated reboots of the system failed to solve problem",
  " Feature was not beta tested",
  " Domain controller not responding",
  " Someone else stole your IP address, call the Internet detectives!",
  " It's not RFC-822 compliant.",
  " operation failed because: there is no message for this error (#1014)",
  " stop bit received",
  " internet is needed to catch the etherbunny",
  " network down, IP packets delivered via UPS",
  " Firmware update in the coffee machine",
  " Temporal anomaly",
  " Mouse has out-of-cheese-error",
  " Borg implants are failing",
  " Borg nanites have infested the server",
  " error: one bad user found in front of screen",
  " Please state the nature of the technical emergency",
  " Internet shut down due to maintenance",
  " Daemon escaped from pentagram",
  " crop circles in the corn shell",
  " sticky bit has come loose",
  " Hot Java has gone cold",
  " Cache miss - please take better aim next time",
  " Hash table has woodworm",
  " Trojan horse ran out of hay",
  " Zombie processes detected, machine is haunted.",
  " overflow error in /dev/null",
  " Browser's cookie is corrupted -- someone's been nibbling on it",
  " Mailer-daemon is busy burning your message in hell.",
  " According to Microsoft, it's by design",
  " vi needs to be upgraded to vii",
  " greenpeace free'd the mallocs",
  " Terrorists crashed an airplane into the server room, have to remove /bin/laden. (rm -rf /bin/laden)",
  " astropneumatic oscillations in the water-cooling",
  " Somebody ran the operating system through a spelling checker",
  " Spider infestation in warm case parts",
  " Brain fried -- Core dumped",
  " Bus error -- driver will be fired.",
  " Bus error -- please leave by the rear door.",
  " Memory fault - where am I?",
  " Memory fault -- brain fried",
  " Memory fault -- core...uh...um...core... Oh dammit, I forget!",
  " Overflow on /dev/null, please empty the bit bucket.",
  " Overload -- core meltdown sequence initiated.",
  " panic: kernel segmentation violation. core dumped		(only kidding)",
  " panic: kernel trap (ignored)",
  " Can't open /usr/share/games/fortunes/fortunes.  Lid stuck on cookie jar.",
  " Your computer account is overdrawn.  Please see Big Brother.",
  " Your fault -- core dumped",
  " Your files are now being encrypted and thrown into the bit bucket.\nEOF",
  " This file will self-destruct in five minutes.",
  " This is an unauthorized cybernetic announcement.",
  " Your mode of life will be changed to ASCII.",
  " Your mode of life will be changed to EBCDIC."
};

void
biomcmc_fprintf_fortune (FILE *stream)
{
  int idx;
  biomcmc_random_number_init (0);
  idx = biomcmc_rng_unif_int (biomcmc_fortune_cookies_size); // 1, 4 = bold, blue
  fprintf (stream, "%s'''%s'''%s\n", prt_col[1][4], biomcmc_fortune_cookies[idx], prt_col_reset);
  biomcmc_random_number_finalize();
}

void
biomcmc_fprintf_bofh (FILE *stream)
{
  int idx;
  biomcmc_random_number_init (0);
  idx = biomcmc_rng_unif_int (biomcmc_fortune_bofh_size); // 0/1, 1 = regular/bold, red
  fprintf (stream, "%s'''%s'''%s\n", prt_col[0][1], biomcmc_fortune_bofh[idx], prt_col_reset);
  biomcmc_random_number_finalize();
}

void
biomcmc_fprintf_colour (FILE *stream, int regular, int colour, const char *message, const char *normaltext, ...)
{
  va_list ap;
  if ((regular < 0) || (regular > 6)) regular = 0;
  if ((colour < 0) || (colour > 7)) colour = 1;
  fprintf (stream, "%s%s%s", prt_col[regular][colour], message, prt_col_reset);
  va_start (ap, normaltext);
  vfprintf (stream, normaltext, ap);
  va_end (ap);
}
