/* 
 * This file is part of biomcmc-lib, a low-level library for phylogenomic analysis.
 * Copyright (C) 2019-today  Leonardo de Oliveira Martins [ leomrtns at gmail.com;  http://www.leomartins.org ]
 *
 * biomcmc is free software; you can redistribute it and/or modify it under the terms of the GNU General Public
 * License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later
 * version.
 *
 * This program is distributed in the hope that it will be usefulull, but WITHOUT ANY WARRANTY; without even the implied 
 * warranty of MERCHANTABILITY or FITNESS FOR A PARTICullAR PURPOSE.  See the GNU General Public License for more 
 * details (file "COPYING" or http://www.gnu.org/copyleft/gpl.html).
 */

/*! \file fortune_cookies.h 
 *  \brief List of inspirational quotes from the linux package `fortune` 
 */

#ifndef _biomcmc_fortune_cookies_h_
#define _biomcmc_fortune_cookies_h_

const char biomcmc_prt_col_reset[] = "\e[0m";
const char biomcmc_prt_col[][8]={ // 0-black   1-red   2-grn   3-yel   4-blu   5-mag   6-cyn   7-white
   {"\e[0;30m",  "\e[0;31m",  "\e[0;32m",  "\e[0;33m",  "\e[0;34m",  "\e[0;35m",  "\e[0;36m",  "\e[0;37m"},  // 0 regular text
   {"\e[1;30m",  "\e[1;31m",  "\e[1;32m",  "\e[1;33m",  "\e[1;34m",  "\e[1;35m",  "\e[1;36m",  "\e[1;37m"},  // 1 regular bold text
   {"\e[4;30m",  "\e[4;31m",  "\e[4;32m",  "\e[4;33m",  "\e[4;34m",  "\e[4;35m",  "\e[4;36m",  "\e[4;37m"},  // 2 regular underline text
   {"\e[40m",    "\e[41m",    "\e[42m",    "\e[43m",    "\e[44m",    "\e[45m",    "\e[46m",    "\e[47m"},    // 3 regular background
   {"\e[0;100m", "\e[0;101m", "\e[0;102m", "\e[0;103m", "\e[0;104m", "\e[0;105m", "\e[0;106m", "\e[0;107m"}, // 4 high intensity underground
   {"\e[0;90m",  "\e[0;91m",  "\e[0;92m",  "\e[0;93m",  "\e[0;94m",  "\e[0;95m",  "\e[0;96m",  "\e[0;97m"},  // 5 high intensity text 
   {"\e[1;90m",  "\e[1;91m",  "\e[1;92m",  "\e[1;93m",  "\e[1;94m",  "\e[1;95m",  "\e[1;96m",  "\e[1;97m"}   // 6 bold high intensity text
};

const uint16_t biomcmc_fortune_cookies_size = 288;
const char *biomcmc_fortune_cookies[] = {
  " A bug in the code is worth two in the documentation.",
  " A bug in the hand is better than one as yet undetected.",
  " A complex system that works is invariably found to have evolved from a\n simple system that works.",
  " A computer scientist is someone who fixes things that aren't broken.",
  " A hacker does for love what others would not do for money.",
  " A language that doesn't affect the way you think about programming is not worth knowing.",
  " A language that doesn't have everything is actually easier to program in than some that do. -- Dennis M. Ritchie",
  " A large number of installed systems work by fiat.  That is, they work by being declared to work. -- Anatol Holt",
  " A list is only as strong as its weakest link. -- Don Knuth",
  " A nasty looking dwarf throws a knife at you.",
  " A successful [software] tool is one that was used to do something undreamed of by its author. -- S. C. Johnson",
  " All constants are variables.",
  " All the simple programs have been written.",
  " And on the seventh day, He exited from append mode.",
  " Another megabytes the dust.",
  " Any given program will expand to fill available memory.",
  " Any given program, when running, is obsolete.",
  " Any program which runs right is obsolete.",
  " Any programming language is at its best before it is implemented and used.",
  " As a computer, I find your faith in technology amusing.",
  " As far as we know, our computer has never had an undetected error. -- Weisert",
  " As of next Tuesday, C will be flushed in favor of COBOL. Please update your programs.",
  " As of next week, passwords will be entered in Morse code.",
  " As Will Rogers would have said, \"There is no such things as a free variable.\"",
  " ASCII a stupid question, you get an EBCDIC answer.",
  " ASHes to ASHes, DOS to DOS.",
  " Asynchronous inputs are at the root of our race problems. -- D. Winker and F. Prosser",
  " At the source of every error which is blamed on the computer you will find at least two human errors, including the error of blaming it on the computer.",
  " BASIC is the Computer Science equivalent of `Scientific Creationism'.",
  " Brain fried -- Core dumped",
  " Breadth-first search is the bulldozer of science. -- Randy Goebel",
  " Can't open /usr/share/games/fortunes/fortunes.  Lid stuck on cookie jar.",
  " Beware of bugs in the above code; I have only proved it correct, not tried it. -- Donald Knuth",
  " Beware of Programmers who carry screwdrivers. -- Leonard Brandwein",
  " Bus error -- driver executed.",
  " Bus error -- please leave by the rear door.",
  " Computers are not intelligent.  They only think they are.",
  " Computer programmers never die, they just get lost in the processing.",
  " Computers are unreliable, but humans are even more unreliable. Any system which depends on human reliability is unreliable. -- Gilb",
  " Computers are useless.  They can only give you answers.	-- Pablo Picasso",
  " Coding is easy;  All you do is sit staring at a terminal until the drops of blood form on your forehead.",
  " Disc space -- the final frontier!",
  " DISCLAIMER: Use of this advanced computing technology does not imply an endorsement of Western industrial civilization.",
  " Disclaimer: These opinions are my own, though for a small fee they be yours too. -- Dave Haynie",
  " Disraeli was pretty close: actually, there are Lies, Damn lies, Statistics, Benchmarks, and Delivery dates.",
  " Don't sweat it -- it's only ones and zeros. -- P. Skelly",
  " Due to lack of disk space, this fortune database has been discontinued.",
  " E Pluribus Unix",
  " FORTH IF HONK THEN",
  " Happiness is twin floppies.",
  " Help me, I'm a prisoner in a Fortune cookie file!",
  " Help!  I'm trapped in a PDP 11/70!",
  " HELP!!!! I'm being held prisoner in /usr/games/lib!",
  " Heuristics are bug ridden by definition.  If they didn't have bugs, then they'd be algorithms.",
  " I came, I saw, I deleted all your files.",
  " I do not fear computers.  I fear the lack of them. -- Isaac Asimov",
  " I wish you humans would leave me alone.",
  " If a listener nods his head when you're explaining your program, wake him up.",
  " If a train station is a place where a train stops, what's a workstation?",
  " If at first you don't succeed, you must be a programmer.",
  " If it has syntax, it isn't user friendly.",
  " If it happens once, it's a bug.\nIf it happens twice, it's a feature.\nIf it happens more than twice, it's a design philosophy.",
  " If the code and the comments disagree, then both are probably wrong. -- Norm Schryer",
  " If you have a procedure with 10 parameters, you probably missed some.",
  " If you think the system is working, ask someone who's waiting for a prompt.",
  " If this is timesharing, give me my share right now.",
  " Intel CPUs are not defective, they just act that way. -- Henry Spencer",
  " Is your job running?  You'd better go catch it!",
  " [It is] best to confuse only one issue at a time. -- K&R",
  " It isn't easy being the parent of a six-year-old.  However, it's a pretty small price to pay for having somebody around the house who understands computers.",
  " It's ten o'clock; do you know where your processes are?",
  " Let the machine do the dirty work. -- \"Elements of Programming Style\", Kernighan and Ritchie",
  " Life would be so much easier if we could just look at the source code. -- Dave Olson",
  " Long computations which yield zero are probably all for naught.",
  " May all your PUSHes be POPped.",
  " Memory fault - where am I?",
  " Memory fault -- brain fried",
  " Memory fault -- core...uh...um...core... Oh dammit, I forget!",
  " MSDOS is not dead, it just smells that way. -- Henry Spencer",
  " Much of the excitement we get out of our work is that we don't really know what we are doing.	-- E. Dijkstra",
  " Nearly every complex solution to a programming problem that I have looked at carefully has turned out to be wrong.	-- Brent Welch",
  " Never make anything simple and efficient when a way can be found to make it complex and wonderful.",
  " Never put off till run-time what you can do at compile-time.	-- D. Gries",
  " Never test for an error condition you don't know how to handle.	-- Steinbach",
  " Old mail has arrived.",
  " Old programmers never die, they just branch to a new address.",
  " Old programmers never die, they just hit account block limit.",
  " On a clear disk you can seek forever. -- P. Denning",
  " On the Internet, nobody knows you're a dog. -- Cartoon caption",
  " One good reason why computers can do more work than people is that they never have to stop and answer the phone.",
  " ... one of the main causes of the fall of the Roman Empire was that, lacking zero, they had no way to indicate successful termination of their C programs.	-- Robert Firth",
  " No man is an island if he's on at least one mailing list.",
  " No part of this message may reproduce, store itself in a retrieval system, or transmit disease, in any form, without the permissiveness of the author.	-- Chris Shaw",
  " Nobody said computers were going to be polite.",
  " Nobody's gonna believe that computers are intelligent until they start coming in late and lying about it.",
  " One person's error is another person's data.",
  " One picture is worth 128K words.",
  " Only great masters of style can succeed in being obtuse. -- Oscar Wilde\nMost UNIX programmers are great masters of style. -- The Unnamed Usenetter",
  " Over the shoulder supervision is more a need of the manager than the programming task.",
  " Overflow on /dev/null, please empty the bit bucket.",
  " Overload -- core meltdown sequence initiated.",
  " panic: kernel segmentation violation. core dumped		(only kidding)",
  " panic: kernel trap (ignored)",
  " Premature optimization is the root of all evil. -- D. E. Knuth",
  " Profanity is the one language all programmers know best.",
  " Real computer scientists don't comment their code.  The identifiers are so long they can't afford the disk space.",
  " Real computer scientists don't program in assembler.  They don't write in anything less portable than a number two pencil.",
  " Real programmers don't comment their code.  It was hard to write, it should be hard to understand.",
  " Real programmers don't draw flowcharts. Flowcharts are, after all, the illiterate's form of documentation.  Cavemen drew flowcharts; look how much good it did them.",
  " Real programmers don't bring brown-bag lunches. If the vending machine doesn't sell it, they don't eat it.  Vending machines don't sell quiche.",
  " Real software engineers don't debug programs, they verify correctness. This process doesn't necessarily involve execution of anything on a computer, except perhaps a Correctness Verification Aid package.",
  " Real Users are afraid they'll break the machine -- but they're never afraid to break your face.",
  " Real Users find the one combination of bizarre input values that shuts down the system for days.",
  " Real Users hate Real Programmers.",
  " Real Users know your home telephone number.",
  " Real Users never know what they want, but they always know when your program doesn't deliver it.",
  " Real Users never use the Help key.",
  " Save energy:  Drive a smaller shell.",
  " Save gas, don't use the shell.",
  " Save yourself!  Reboot in 5 seconds!",
  " Say \"twenty-three-skiddoo\" to logout.",
  " Science is to computer science as hydrodynamics is to plumbing.",
  " She sells cshs by the cshore.",
  " Some of my readers ask me what a \"Serial Port\" is. The answer is: I don't know. Is it some kind of wine you have with breakfast?",
  " Some people claim that the UNIX learning curve is steep, but at least you only have to climb it once.",
  " Somebody's terminal is dropping bits.  I found a pile of them over in the corner.",
  " Staff meeting in the conference room in \%d minutes.",
  " Staff meeting in the conference room in 3 minutes.",
  " Standards are crucial.  And the best thing about standards is: there are so many to choose from!",
  " The \"cutting edge\" is getting rather dull. -- Andy Purshottam",
  " The algorithm for finding the longest path in a graph is NP-complete. For you systems people, that means it's *real slow*. -- Bart Miller",
  " The C Programming Language -- A language which combines the flexibility of assembly language with the power of assembly language.",
  " The Computer made me do it.",
  " The computing field is always in need of new cliches. -- Alan Perlis",
  " The difference between art and science is that science is what we understand well enough to explain to a computer.  Art is everything else.	-- Donald Knuth, 'Discover'",
  " The disks are getting full; purge a file today.",
  " The eleventh commandment was `Thou Shalt Compute' or `Thou Shalt Not Compute' -- I forget which.",
  " The less time planning, the more time programming.",
  " The meat is rotten, but the booze is holding out. Computer translation of 'The spirit is willing, but the flesh is weak.'",
  " The nice thing about standards is that there are so many of them to choose from. -- Andrew S. Tanenbaum",
  " The number of arguments is unimportant unless some of them are correct. -- Ralph Hartley",
  " The number of computer scientists in a room is inversely proportional to the number of bugs in their code.",
  " The number of UNIX installations has grown to 10, with more expected. -- The Unix Programmer's Manual, 2nd Edition, June 1972",
  " The world is coming to an end ... SAVE YOUR BUFFERS!!!",
  " The world is coming to an end.  Please log off.",
  " The world is not octal despite DEC.",
  " The trouble with computers is that they do what you tell them, not what you want.		-- D. Cohen",
  " The value of a program is proportional to the weight of its output.",
  " There are no games on this system.",
  " There are running jobs.  Why don't you go chase them?",
  " There are two ways to write error-free programs; only the third one works.",
  " This file will self-destruct in five minutes.",
  " This is an unauthorized cybernetic announcement.",
  " This login session: $13.76, but for you $11.88.",
  " This process can check if this value is zero, and if it is, it does something child-like.		-- Forbes Burkowski, CS 454, University of Washington",
  " This screen intentionally left blank.",
  " Those who can't write, write manuals.",
  " Those who do not understand Unix are condemned to reinvent it, poorly. -- Henry Spencer",
  " This system will self-destruct in five minutes.",
  " After three days without programming, life becomes meaningless.	-- Geoffrey James, 'The Tao of Programming'",
  " Let the programmers be many and the managers few -- then all will	be productive. -- Geoffrey James, 'The Tao of Programming'",
  " Time for you to leave.	-- Geoffrey James, 'The Tao of Programming'",
  " Without the wind, the grass does not move.  Without software, hardware is useless.-- Geoffrey James, 'The Tao of Programming'",
  " To err is human -- to blame it on a computer is even more so.",
  " To err is human, to forgive, beyond the scope of the Operating System.",
  " To iterate is human, to recurse, divine. -- Robert Heller",
  " To the systems programmer, users and applications serve only to provide a test load.",
  " Truly simple systems... require infinite testing. -- Norman Augustine",
  " Trying to establish voice contact ... please yell into keyboard.",
  " Variables don't; constants aren't.",
  " We are experiencing system trouble -- do not adjust your terminal.",
  " We are Microsoft.  Unix is irrelevant.  Openness is futile.  Prepare to be assimilated.",
  " We don't really understand it, so we'll give it to the programmers.",
  " When someone says \"I want a programming language in which I need only say what I wish done,\" give him a lollipop.",
  " When we write programs that 'learn', it turns out we do and they don't.",
  " Whom computers would destroy, they must first drive mad.",
  " Within a computer, natural language is unnatural.",
  " You are an insult to my intelligence!  I demand that you log off immediately.",
  " You are false data.",
  " You are in a maze of little twisting passages, all alike.",
  " You are in a maze of little twisting passages, all different.",
  " You are in the hall of the mountain king.",
  " You are lost in the Swamps of Despair.",
  " You can tune a piano, but you can't tuna fish.\nYou can tune a filesystem, but you can't tuna fish.\n-- from the tunefs(8) man page",
  " You can't go home again, unless you set \$HOME.",
  " You can't make a program without broken egos.",
  " You don't have to know how the computer works, just how to work the computer.",
  " You had mail, but the super-user read it, and deleted it!",
  " You had mail. Paul read it, so ask him what it said.",
  " You have a tendency to feel you are superior to most computers.",
  " You have junk mail.",
  " Don't fear the pen. When in doubt, draw a pretty picture. -- Baker's Third Law of Design.",
  " Life is NP-hard, and then you die. -- Dave Cock",
  " Try to remove the color-problem by restarting your computer several times. -- Microsoft Internet Explorer's README.TXT",
  " You will have many recoverable tape errors.",
  " You will lose an important disk file.",
  " You will lose an important tape file.",
  " You're not Dave.  Who are you?",
  " You're using a keyboard!  How quaint!",
  " Your code should be more efficient!",
  " Your computer account is overdrawn.  Please reauthorize.",
  " Your computer account is overdrawn.  Please see Big Brother.",
  " Your fault -- core dumped",
  " Your files are now being encrypted and thrown into the bit bucket.\nEOF",
  " Your mode of life will be changed to ASCII.",
  " Your mode of life will be changed to EBCDIC.",
  " Your password is pitifully obvious.",
  " Your program is sick!  Shoot it and put it out of its memory.",
  " We have a policy that we are not being hacked. -- Lisa Kopp, Friendster rep, commenting on a security flaw",
  " You might have mail.",
  " You can't just ask customers what they want and then try to give that to them. By the time you get it built, they'll want something new. -- Steve Jobs (1955-2011)",
  " UNIX is very simple, it just needs a genius to understand its simplicity. -- Dennis Ritchie (1941-2011)",
  " C is quirky, flawed, and an enormous success. -- Dennis Ritchie (1941-2011)",
  " When I read commentary about suggestions for where C should go, I often think back and give thanks that it wasn't developed under the advice of a worldwide crowd. -- Dennis Ritchie (1941-2011)",
  " To tell the truth, I don't know how Linus and his merry band manage so well -- I couldn't have stood it with C. -- Dennis Ritchie (1941-2011)", 
  " Mathematics is made of 50 percent formulas, 50 percent proofs, and 50 percent imagination. ",
  " A mathematician is a device for turning coffee into theorems (-- P. Erdos)Addendum: American coffee is good for lemmas.",
  " An engineer thinks that his equations are an approximation to reality. A physicist thinks reality is an approximation to his equations. A mathematician doesn't care. ",
  " Old mathematicians never die; they just lose some of their functions. ",
  " Mathematics is the art of giving the same name to different things. -- J. H. Poincare",
  " There is no logical foundation of mathematics, and Gödel has proved it! ",
  " A topologist is a person who doesn't know the difference between a coffee cup and a doughnut. ",
  " Classification of mathematical problems as linear and nonlinear is like classification of the Universe as bananas and non-bananas. ",
  " Why was six afraid of seven? Because 7 8 9.",
  " What did one math book say to the other? Don\'t bother me I\'ve got my own problems!",
  " Don\'t anthropomorphize computers, they don\'t like it.",
  " Three statisticians went duck hunting. A duck was approaching and the first statistician shot, And missed the duck by being a foot too high. The secondshot and was a foot too low. The third cried, \"We hit it!\"",
  " Two is the oddest prime of all, because it\'s the only one that\'s even!",
  " Several scientists were asked to prove that all odd integers higher than 2 are prime.\n Mathematician: 3 is a prime, 5 is a prime, 7 is a prime, and by induction - every odd integer higher than 2 is a prime.\n Physicist: 3 is a prime, 5 is a prime, 7 is a prime, 9 is an experimental error, 11 is a prime. Just to be sure, try several randomly chosen numbers: 17 is a prime, 23 is a prime...\n Engineer: 3 is a prime, 5 is a prime, 7 is a prime, 9 is an approximation to a prime, 11 is a prime,...\n Programmer (reading the output on the screen): 3 is a prime, 3 is a prime, 3 a is prime, 3 is a prime....\n Biologist: 3 is a prime, 5 is a prime, 7 is a prime, 9 -- results have not arrived yet,...\n ",
  " This is a one line proof...if we start sufficiently far to the left.",
  " The problems for the exam will be similar to the discussed in the class. Of course, the numbers will be different. But not all of them. Pi will still be 3.14159...",
  " Proof by forward reference:Reference is usually to a forthcoming paper of the author, which is often not as forthcoming as at first.",
  " Proof by funding:How could three different government agencies be wrong?",
  " Mathematical definition of TRIVIAL:If I have to show you how to do this, you're in the wrong class.",
  " Mathematical definition of SKETCH OF A PROOF:I couldn\'t verify all the details, so I\'ll break it down into the parts I couldn\'t prove.",
  " Mathematical definition of CANONICAL FORM:4 out of 5 mathematicians surveyed recommended this as the final form for their students who choose to finish.",
  " Mathematical definition of TWO LINE PROOF:I\'ll leave out everything but the conclusion, you can\'t question \'em if you can\'t see \'em.",
  " Mathematical definition of BRIEFLY:I\'m running out of time, so I\'ll just write and talk faster.",
  " Mathematical definition of LET'S TALK THROUGH IT:I don\'t want to write it on the board lest I make a mistake.",
  " The highest moments in the life of a mathematician are the first few moments after one has proved the result, but before one finds the mistake. ",
  " The highest moments in the life of a programmer are the first few moments after one has compiled the code, but before one finds the bug. ",
  " Relations between pure and applied mathematicians are based on trust and understanding. Namely, pure mathematicians do not trust applied mathematicians, and applied mathematicians do not understand pure mathematicians. ",
  " If I have not seen as far as others, it is because giants were standing on my shoulders. (-- Hal Abelson)",
  " Mathematicians stand on each other\'s shoulders (-- Gauss). Mathematicians stand on each other\'s shoulders while computer scientists stand on each other\'s toes. (-- Richard Hamming)",
  " Q: Why do Computer Scientists get Halloween and Christmas mixed up?A: Because Oct. 31 = Dec. 25.",
  " Q:What is a dilemma?A: A lemma that proves two results.\n" ,
  " A bank is a place where they lend you an umbrella in fair weather and ask for it back the when it begins to rain. -- Robert Frost",
  " A budget is just a method of worrying before you spend money, as well as afterward.",
  " A committee is a group that keeps the minutes and loses hours. -- Milton Berle",
  " A committee is a life form with six or more legs and no brain. -- Lazarus Long, \"Time Enough For Love\"",
  " A committee takes root and grows, it flowers, wilts and dies, scattering the seed from which other committees will bloom. -- Parkinson",
  " A company is known by the men it keeps.",
  " A consultant is a person who borrows your watch, tells you what time it is, pockets the watch, and sends you a bill for it.",
  " A continuing flow of paper is sufficient to continue the flow of paper. -- Dyer",
  " A verbal contract isn't worth the paper it's written on. -- Samuel Goldwyn",
  " About the time we think we can make ends meet, somebody moves the ends. -- Herbert Hoover",
  " After all is said and done, a hell of a lot more is said than done.",
  " All I ask is a chance to prove that money can't make me happy.",
  " At these prices, I lose money -- but I make it up in volume. -- Peter G. Alaquon",
  " By working faithfully eight hours a day, you may eventually get to be boss and work twelve. -- Robert Frost",
  " Exceptions prove the rule, and wreck the budget. -- Miller",
  " Executive ability is deciding quickly and getting somebody else to do the work. -- John G. Pollard",
  " Good day to avoid cops.  Crawl to work.",
  " Honesty pays, but it doesn't seem to pay enough to suit some people. -- F. M. Hubbard",
  " Hotels are tired of getting ripped off.  I checked into a hotel and they had towels from my house. -- Mark Guido",
  " How come everyone's going so slow if it's called rush hour?",
  " - How many people work here? \n - Oh, about half.",
  " I don't want to achieve immortality through my work.  I want to achieve immortality through not dying. -- Woody Allen",
  " I've got all the money I'll ever need if I die by 4 o'clock. -- Henny Youngman",
  " If all else fails, lower your standards.",
  " If I want your opinion, I'll ask you to fill out the necessary form.",
  " If you can't get your work done in the first 24 hours, work nights.",
  " If you can't learn to do it well, learn to enjoy doing it badly.",
  " If you don't have time to do it right, where are you going to find the time to do it over?",
  " Keep up the good work!  But please don't ask me to help.",
  " Living on Earth may be expensive, but it includes an annual free trip around the Sun.",
  " Remember -- only 10\% of anything can be in the top 10\%.",
  " The trouble with being punctual is that nobody's there to appreciate it. -- Franklin P. Jones",
  " The trouble with being punctual is that people think you have nothing more important to do.",
  " The trouble with money is it costs too much!",
  " There's nothing worse for your business than extra Santa Clauses smoking in the men's room. -- W. Bossert",
  " When your work speaks for itself, don't interrupt. -- Henry J. Kaiser",
  " When you don't know what to do, walk fast and look worried.",
  " Where there's a will, there's a relative.",
  " Where there's a will, there's an Inheritance Tax.",
  " We were so poor that we thought new clothes meant someone had died.",
  " We're living in a golden age.  All you need is gold. -- D. W. Robertson.",
  " Weekend, where are you?"}; 

const uint16_t biomcmc_fortune_bofh_size = 447; 
const char *biomcmc_fortunes_bofh[] = {
  "#2: solar flares",
  "#3: electromagnetic radiation from satellite debris",
  "#4: static from nylon underwear",
  "#5: static from plastic slide rules",
  "#6: global warming",
  "#7: poor power conditioning",
  "#8: static buildup",
  "#9: doppler effect",
  "#10: hardware stress fractures",
  "#11: magnetic interference from money/credit cards",
  "#12: dry joints on cable plug",
  "#13: we're waiting for [the phone company] to fix that line",
  "#14: sounds like a Windows problem, try calling Microsoft support",
  "#15: temporary routing anomaly",
  "#16: somebody was calculating pi on the server",
  "#17: fat electrons in the lines",
  "#18: excess surge protection",
  "#21: POSIX compliance problem",
  "#22: monitor resolution too high",
  "#23: improperly oriented keyboard",
  "#24: network packets travelling uphill (use a carrier pigeon)",
  "#25: Decreasing electron flux",
  "#26: first Saturday after first full moon in Winter",
  "#27: radiosity depletion",
  "#28: CPU radiator broken",
  "#29: It works the way the Wang did, what's the problem",
  "#30: positron router malfunction",
  "#31: cellular telephone interference",
  "#32: techtonic stress",
  "#33: piezo-electric interference",
  "#34: (l)user error",
  "#35: working as designed (feature not a bug)",
  "#36: dynamic software linking table corrupted",
  "#37: heavy gravity fluctuation, move computer to floor rapidly",
  "#38: your boss plugged hairdryer into UPS",
  "#40: not enough memory, go get system upgrade",
  "#41: interrupt configuration error",
  "#42: spaghetti cable cause packet failure",
  "#43: boss forgot system password",
  "#44: bank holiday - system operating credits  not recharged",
  "#45: virus attack, luser responsible",
  "#46: waste water tank overflowed onto computer",
  "#47: Complete Transient Lockout",
  "#48: bad ether in the cables",
  "#49: Bogon emissions",
  "#50: Change in Earth's rotational speed",
  "#51: Cosmic ray particles crashed through the hard disk platter",
  "#52: Smell from unhygienic janitorial staff wrecked the tape heads",
  "#53: Little hamster in running wheel had coronary; waiting for replacement to be Fedexed from Wyoming",
  "#54: Evil dogs hypnotised the night shift",
  "#55: Plumber mistook routing panel for decorative wall fixture",
  "#56: Electricians made popcorn in the power supply",
  "#57: Groundskeepers stole the root password",
  "#58: high pressure system failure",
  "#59: failed trials, system needs redesigned",
  "#60: system has been recalled",
  "#61: not approved by the FCC",
  "#62: need to wrap system in aluminum foil to fix problem",
  "#63: not properly grounded, please bury computer",
  "#64: CPU needs recalibration",
  "#65: system needs to be rebooted",
  "#66: bit bucket overflow",
  "#67: descramble code needed from software company",
  "#68: only available on a need to know basis",
  "#69: knot in cables caused data stream to become twisted and kinked",
  "#70: nesting roaches shorted out the ether cable",
  "#71: The file system is full of it",
  "#72: Satan did it",
  "#73: Daemons did it",
  "#74: You're out of memory",
  "#76: Unoptimized hard drive",
  "#77: Typo in the code",
  "#78: Yes, yes, its called a design limitation",
  "#79: Look, buddy:  Windows 3.1 IS A General Protection Fault.",
  "#80: That's a great computer you have there; have you considered how it would work as a BSD machine?",
  "#81: Please excuse me, I have to circuit an AC line through my head to get this database working.",
  "#82: Yeah, yo mama dresses you funny and you need a mouse to delete files.",
  "#83: Support staff hung over, send aspirin and come back LATER.",
  "#84: Someone is standing on the ethernet cable, causing a kink in the cable",
  "#85: Windows 95 undocumented \"feature\"",
  "#86: Runt packets",
  "#87: Password is too complex to decrypt",
  "#88: Boss' kid fucked up the machine",
  "#89: Electromagnetic energy loss",
  "#90: Budget cuts",
  "#91: Mouse chewed through power cable",
  "#92: Stale file handle (next time use Tupperware(tm)!)",
  "#93: Feature not yet implemented",
  "#94: Internet outage",
  "#95: Pentium FDIV bug",
  "#96: Vendor no longer supports the product",
  "#97: Small animal kamikaze attack on power supplies",
  "#98: The vendor put the bug there.",
  "#99: SIMM crosstalk.",
  "#100: IRQ dropout",
  "#101: Collapsed Backbone",
  "#102: Power company testing new voltage spike (creation) equipment",
  "#103: operators on strike due to broken coffee machine",
  "#104: backup tape overwritten with copy of system manager's favourite CD",
  "#105: UPS interrupted the server's power",
  "#106: The electrician didn't know what the yellow cable was so he yanked the ethernet out.",
  "#107: The keyboard isn't plugged in",
  "#108: The air conditioning water supply pipe ruptured over the machine room",
  "#109: The electricity substation in the car park blew up.",
  "#110: The rolling stones concert down the road caused a brown out",
  "#111: The salesman drove over the CPU board.",
  "#112: The monitor is plugged into the serial port",
  "#113: Root nameservers are out of sync",
  "#114: electro-magnetic pulses from French above ground nuke testing.",
  "#115: your keyboard's space bar is generating spurious keycodes.",
  "#116: the real ttys became pseudo ttys and vice-versa.",
  "#117: the printer thinks its a router.",
  "#118: the router thinks its a printer.",
  "#119: evil hackers from Serbia.",
  "#120: we just switched to FDDI.",
  "#121: halon system went off and killed the operators.",
  "#122: because Bill Gates is a Jehovah's witness and so nothing can work on St. Swithin's day.",
  "#123: user to computer ratio too high.",
  "#124: user to computer ration too low.",
  "#125: we just switched to Sprint.",
  "#126: it has Intel Inside",
  "#127: Sticky bits on disk.",
  "#128: Power Company having EMP problems with their reactor",
  "#129: The ring needs another token",
  "#130: new management",
  "#131: telnet: Unable to connect to remote host: Connection refused",
  "#132: SCSI Chain overterminated",
  "#133: It's not plugged in.",
  "#134: because of network lag due to too many people playing deathmatch",
  "#135: You put the disk in upside down.",
  "#136: Daemons loose in system.",
  "#137: User was distributing pornography on server; system seized by FBI.",
  "#138: BNC (brain not connected)",
  "#139: UBNC (user brain not connected)",
  "#140: LBNC (luser brain not connected)",
  "#141: disks spinning backwards - toggle the hemisphere jumper.",
  "#142: new guy cross-connected phone lines with ac power bus.",
  "#143: had to use hammer to free stuck disk drive heads.",
  "#144: Too few computrons available.",
  "#145: Flat tire on station wagon with tapes.  (\"Never underestimate the bandwidth of a station wagon full of tapes hurling down the highway\" Andrew S. Tannenbaum) ",
  "#146: Communications satellite used by the military for star wars.",
  "#147: Party-bug in the Aloha protocol.",
  "#148: Insert coin for new game",
  "#149: Dew on the telephone lines.",
  "#150: Arcserve crashed the server again.",
  "#151: Some one needed the powerstrip, so they pulled the switch plug.",
  "#152: My pony-tail hit the on/off switch on the power strip.",
  "#153: Big to little endian conversion error",
  "#154: You can tune a file system, but you can't tune a fish (from most tunefs man pages)",
  "#155: Dumb terminal",
  "#156: Zombie processes haunting the computer",
  "#157: Incorrect time synchronization",
  "#158: Defunct processes",
  "#159: Stubborn processes",
  "#160: non-redundant fan failure ",
  "#161: monitor VLF leakage",
  "#162: bugs in the RAID",
  "#163: no \"any\" key on keyboard",
  "#164: root rot",
  "#165: Backbone Scoliosis",
  "#166: /pub/lunch",
  "#167: excessive collisions & not enough packet ambulances",
  "#168: le0: no carrier: transceiver cable problem?",
  "#169: broadcast packets on wrong frequency",
  "#170: popper unable to process jumbo kernel",
  "#171: NOTICE: alloc: /dev/null: filesystem full",
  "#172: pseudo-user on a pseudo-terminal",
  "#173: Recursive traversal of loopback mount points",
  "#174: Backbone adjustment",
  "#175: OS swapped to disk",
  "#176: vapors from evaporating sticky-note adhesives",
  "#177: sticktion",
  "#178: short leg on process table",
  "#179: multicasts on broken packets",
  "#180: ether leak",
  "#181: Atilla the Hub",
  "#182: endothermal recalibration",
  "#183: filesystem not big enough for Jumbo Kernel Patch",
  "#184: loop found in loop in redundant loopback",
  "#185: system consumed all the paper for paging",
  "#186: permission denied",
  "#187: Reformatting Page. Wait...",
  "#188: ..disk or the processor is on fire.",
  "#189: SCSI's too wide.",
  "#190: Proprietary Information.",
  "#191: Just type 'mv * /dev/null'.",
  "#192: runaway cat on system.",
  "#193: Did you pay the new Support Fee?",
  "#194: We only support a 1200 bps connection.",
  "#195: We only support a 28000 bps connection.",
  "#196: Me no internet, only janitor, me just wax floors.",
  "#197: I'm sorry a pentium won't do, you need an SGI to connect with us.",
  "#198: Post-it Note Sludge leaked into the monitor.",
  "#199: the curls in your keyboard cord are losing electricity.",
  "#200: The monitor needs another box of pixels.",
  "#202: kernel panic: write-only-memory (/dev/wom0) capacity exceeded.",
  "#203: Write-only-memory subsystem too slow for this machine. Contact your local dealer.",
  "#204: Just pick up the phone and give modem connect sounds. \"Well you said we should get more lines so we don't have voice lines.\"",
  "#205: Quantum dynamics are affecting the transistors",
  "#206: Police are examining all internet packets in the search for a narco-net-trafficker",
  "#207: We are currently trying a new concept of using a live mouse.  Unfortunately, one has yet to survive being hooked up to the computer.....please bear with us.",
  "#208: Your mail is being routed through Germany ... and they're censoring us.",
  "#209: Only people with names beginning with 'A' are getting mail this week (a la Microsoft)",
  "#210: We didn't pay the Internet bill and it's been cut off.",
  "#211: Lightning strikes.",
  "#212: Of course it doesn't work. We've performed a software upgrade.",
  "#213: Change your language to Finnish.",
  "#214: Fluorescent lights are generating negative ions. If turning them off doesn't work, take them out and put tin foil on the ends.",
  "#215: High nuclear activity in your area.",
  "#216: What office are you in? Oh, that one.  Did you know that your building was built over the universities first nuclear research site? And wow, aren't you the lucky one, your office is right over where the core is buried!",
  "#217: The MGs ran out of gas.",
  "#218: The UPS doesn't have a battery backup.",
  "#219: Recursivity.  Call back if it happens again.",
  "#220: Someone thought The Big Red Button was a light switch.",
  "#221: The mainframe needs to rest.  It's getting old, you know.",
  "#222: I'm not sure.  Try calling the Internet's head office -- it's in the book.",
  "#223: The lines are all busy (busied out, that is -- why let them in to begin with?).",
  "#224: Jan  9 16:41:27 huber su: 'su root' succeeded for .... on /dev/pts/1",
  "#225: It's those computer people in X {city of world}.  They keep stuffing things up.",
  "#226: A star wars satellite accidently blew up the WAN.",
  "#227: Fatal error right in front of screen",
  "#228: That function is not currently supported, but Bill Gates assures us it will be featured in the next upgrade.",
  "#229: wrong polarity of neutron flow",
  "#230: Lusers learning curve appears to be fractal",
  "#231: We had to turn off that service to comply with the CDA Bill.",
  "#232: Ionization from the air-conditioning",
  "#233: TCP/IP UDP alarm threshold is set too low.",
  "#234: Someone is broadcasting pygmy packets and the router doesn't know how to deal with them.",
  "#235: The new frame relay network hasn't bedded down the software loop transmitter yet. ",
  "#236: Fanout dropping voltage too much, try cutting some of those little traces",
  "#237: Plate voltage too low on demodulator tube",
  "#238: You did wha... oh _dear_....",
  "#239: CPU needs bearings repacked",
  "#240: Too many little pins on CPU confusing it, bend back and forth until 10-20\% are neatly removed. Do _not_ leave metal bits visible!",
  "#241: _Rosin_ core solder? But...",
  "#242: Software uses US measurements, but the OS is in metric...",
  "#243: The computer fleetly, mouse and all.",
  "#244: Your cat tried to eat the mouse.",
  "#245: The Borg tried to assimilate your system. Resistance is futile.",
  "#246: It must have been the lightning storm we had (yesterday) (last week) (last month)",
  "#247: Due to Federal Budget problems we have been forced to cut back on the number of users able to access the system at one time. (namely none allowed....)",
  "#248: Too much radiation coming from the soil.",
  "#249: Unfortunately we have run out of bits/bytes/whatever. Don't worry, the next supply will be coming next week.",
  "#250: Program load too heavy for processor to lift.",
  "#251: Processes running slowly due to weak power supply",
  "#252: Our ISP is having {switching,routing,SMDS,frame relay} problems",
  "#253: We've run out of licenses",
  "#254: Interference from lunar radiation",
  "#255: Standing room only on the bus.",
  "#256: You need to install an RTFM interface.",
  "#257: That would be because the software doesn't work.",
  "#258: That's easy to fix, but I can't be bothered.",
  "#259: Someone's tie is caught in the printer, and if anything else gets printed, he'll be in it too.",
  "#260: We're upgrading /dev/null",
  "#261: The Usenet news is out of date",
  "#262: Our POP server was kidnapped by a weasel.",
  "#263: It's stuck in the Web.",
  "#264: Your modem doesn't speak English.",
  "#265: The mouse escaped.",
  "#266: All of the packets are empty.",
  "#267: The UPS is on strike.",
  "#268: Neutrino overload on the nameserver",
  "#269: Melting hard drives",
  "#270: Someone has messed up the kernel pointers",
  "#271: The kernel license has expired",
  "#272: Netscape has crashed",
  "#273: The cord jumped over and hit the power switch.",
  "#274: It was OK before you touched it.",
  "#275: Bit rot",
  "#276: U.S. Postal Service",
  "#277: Your Flux Capacitor has gone bad.",
  "#278: The Dilithium Crystals need to be rotated.",
  "#279: The static electricity routing is acting up...",
  "#280: Traceroute says that there is a routing problem in the backbone.  It's not our problem.",
  "#281: The co-locator cannot verify the frame-relay gateway to the ISDN server.",
  "#282: High altitude condensation from U.S.A.F prototype aircraft has contaminated the primary subnet mask. Turn off your computer for 9 days to avoid damaging it.",
  "#283: Lawn mower blade in your fan need sharpening",
  "#284: Electrons on a bender",
  "#285: Telecommunications is upgrading. ",
  "#286: Telecommunications is downgrading.",
  "#287: Telecommunications is downshifting.",
  "#288: Hard drive sleeping. Let it wake up on it's own...",
  "#289: Interference between the keyboard and the chair.",
  "#290: The CPU has shifted, and become decentralized.",
  "#291: Due to the CDA, we no longer have a root account.",
  "#292: We ran out of dial tone and we're and waiting for the phone company to deliver another bottle.",
  "#293: You must've hit the wrong any key.",
  "#294: PCMCIA slave driver",
  "#295: The Token fell out of the ring. Call us when you find it.",
  "#296: The hardware bus needs a new token.",
  "#297: Too many interrupts",
  "#298: Not enough interrupts",
  "#299: The data on your hard drive is out of balance.",
  "#300: Digital Manipulator exceeding velocity parameters",
  "#301: appears to be a Slow/Narrow SCSI-0 Interface problem",
  "#302: microelectronic Riemannian curved-space fault in write-only file system",
  "#303: fractal radiation jamming the backbone",
  "#304: routing problems on the neural net",
  "#305: IRQ-problems with the Un-Interruptible-Power-Supply",
  "#306: CPU-angle has to be adjusted because of vibrations coming from the nearby road",
  "#307: emissions from GSM-phones",
  "#308: CD-ROM server needs recalibration",
  "#309: firewall needs cooling",
  "#310: asynchronous inode failure",
  "#311: transient bus protocol violation",
  "#312: incompatible bit-registration operators",
  "#313: your process is not ISO 9000 compliant",
  "#314: You need to upgrade your VESA local bus to a MasterCard local bus.",
  "#315: The recent proliferation of Nuclear Testing",
  "#316: Elves on strike. (Why do they call EMAG Elf Magic)",
  "#317: Internet exceeded Luser level, please wait until a luser logs off before attempting to log back on.",
  "#318: Your EMAIL is now being delivered by the USPS.",
  "#319: Your computer hasn't been returning all the bits it gets from the Internet.",
  "#320: You've been infected by the Telescoping Hubble virus.",
  "#321: Scheduled global CPU outage",
  "#322: Your Pentium has a heating problem - try cooling it with ice cold water.(Do not turn of your computer, you do not want to cool down the Pentium Chip while he isn't working, do you?)",
  "#323: Your processor has processed too many instructions.  Turn it off immediately, do not type any commands!!",
  "#324: Your packets were eaten by the terminator",
  "#325: Your processor does not develop enough heat.",
  "#326: We need a licensed electrician to replace the light bulbs in the computer room.",
  "#327: The POP server is out of Coke",
  "#328: Fiber optics caused gas main leak",
  "#329: Server depressed, needs Prozac",
  "#330: quantum decoherence",
  "#331: those damn raccoons!",
  "#332: suboptimal routing experience",
  "#333: A plumber is needed, the network drain is clogged",
  "#334: 50\% of the manual is in .pdf readme files",
  "#335: the AA battery in the wallclock sends magnetic interference",
  "#336: the xy axis in the trackball is coordinated with the summer solstice",
  "#337: the butane lighter causes the pincushioning",
  "#338: old inkjet cartridges emanate barium-based fumes",
  "#339: manager in the cable duct",
  "#340: Well fix that in the next (upgrade, update, patch release, service pack).",
  "#341: HTTPD Error 666 : BOFH was here",
  "#342: HTTPD Error 4004 : very old Intel cpu - insufficient processing power",
  "#343: The ATM board has run out of 10 pound notes.  We are having a whip round to refill it, care to contribute ?",
  "#344: Network failure -  call NBC",
  "#345: Having to manually track the satellite.",
  "#346: Your/our computer(s) had suffered a memory leak, and we are waiting for them to be topped up.",
  "#347: The rubber band broke",
  "#348: We're on Token Ring, and it looks like the token got loose.",
  "#349: Stray Alpha Particles from memory packaging caused Hard Memory Error on Server.",
  "#350: paradigm shift...without a clutch",
  "#351: PEBKAC (Problem Exists Between Keyboard And Chair)",
  "#352: The cables are not the same length.",
  "#353: Second-system effect.",
  "#354: Chewing gum on /dev/sd3c",
  "#355: Boredom in the Kernel.",
  "#356: the daemons! the daemons! the terrible daemons!",
  "#357: I'd love to help you -- it's just that the Boss won't let me near the computer. ",
  "#358: struck by the Good Times virus",
  "#359: YOU HAVE AN I/O ERROR -> Incompetent Operator error",
  "#360: Your parity check is overdrawn and you're out of cache.",
  "#361: Communist revolutionaries taking over the server room and demanding all the computers in the building or they shoot the sysadmin. Poor misguided fools.",
  "#362: Plasma conduit breach",
  "#363: Out of cards on drive D: ",
  "#364: Sand fleas eating the Internet cables",
  "#365: parallel processors running perpendicular today",
  "#366: ATM cell has no roaming feature turned on, notebooks can't connect",
  "#367: Webmasters kidnapped by evil cult.",
  "#368: Failure to adjust for daylight savings time.",
  "#369: Virus transmitted from computer to sysadmins.",
  "#370: Virus due to computers having unsafe sex.",
  "#371: Incorrectly configured static routes on the corerouters.",
  "#372: Forced to support NT servers; sysadmins quit.",
  "#373: Suspicious pointer corrupted virtual machine",
  "#374: It's the InterNIC's fault.",
  "#375: Root name servers corrupted.",
  "#376: Budget cuts forced us to sell all the power cords for the servers.",
  "#377: Someone hooked the twisted pair wires into the answering machine.",
  "#378: Operators killed by year 2000 bug bite.",
  "#379: We've picked COBOL as the language of choice.",
  "#380: Operators killed when huge stack of backup tapes fell over.",
  "#381: Robotic tape changer mistook operator's tie for a backup tape.",
  "#382: Someone was smoking in the computer room and set off the halon systems.",
  "#383: Your processor has taken a ride to Heaven's Gate on the UFO behind Hale-Bopp's comet.",
  "#384: it's an ID-10-T error",
  "#385: Dyslexics retyping hosts file on servers",
  "#386: The Internet is being scanned for viruses.",
  "#387: Your computer's union contract is set to expire at midnight.",
  "#388: Bad user karma.",
  "#389: /dev/clue was linked to /dev/null",
  "#390: Increased sunspot activity.",
  "#391: We already sent around a notice about that.",
  "#392: It's union rules. There's nothing we can do about it. Sorry.",
  "#393: Interference from the Van Allen Belt.",
  "#394: Jupiter is aligned with Mars.",
  "#395: Redundant ACLs. ",
  "#396: Mail server hit by UniSpammer.",
  "#397: T-1's congested due to porn traffic to the news server.",
  "#398: Data for intranet got routed through the extranet and landed on the internet.",
  "#399: We are a 100\% Microsoft Shop.",
  "#400: We are Microsoft.  What you are experiencing is not a problem; it is an undocumented feature.",
  "#401: Sales staff sold a product we don't offer.",
  "#402: Secretary sent chain letter to all 5000 employees.",
  "#403: Sysadmin didn't hear pager go off due to loud music from bar-room speakers.",
  "#404: Sysadmin accidentally destroyed pager with a large hammer.",
  "#405: Sysadmins unavailable because they are in a meeting talking about why they are unavailable so much.",
  "#406: Bad cafeteria food landed all the sysadmins in the hospital.",
  "#407: Route flapping at the NAP.",
  "#408: Computers under water due to SYN flooding.",
  "#409: The vulcan-death-grip ping has been applied.",
  "#410: Electrical conduits in machine room are melting.",
  "#411: Traffic jam on the Information Superhighway.",
  "#412: Radial Telemetry Infiltration",
  "#413: Cow-tippers tipped a cow onto the server.",
  "#414: tachyon emissions overloading the system",
  "#415: Maintenance window broken",
  "#416: We're out of slots on the server",
  "#417: Computer room being moved.  Our systems are down for the weekend.",
  "#418: Sysadmins busy fighting SPAM.",
  "#419: Repeated reboots of the system failed to solve problem",
  "#420: Feature was not beta tested",
  "#421: Domain controller not responding",
  "#422: Someone else stole your IP address, call the Internet detectives!",
  "#423: It's not RFC-822 compliant.",
  "#424: operation failed because: there is no message for this error (#1014)",
  "#425: stop bit received",
  "#426: internet is needed to catch the etherbunny",
  "#427: network down, IP packets delivered via UPS",
  "#428: Firmware update in the coffee machine",
  "#429: Temporal anomaly",
  "#430: Mouse has out-of-cheese-error",
  "#431: Borg implants are failing",
  "#432: Borg nanites have infested the server",
  "#433: error: one bad user found in front of screen",
  "#434: Please state the nature of the technical emergency",
  "#435: Internet shut down due to maintenance",
  "#436: Daemon escaped from pentagram",
  "#437: crop circles in the corn shell",
  "#438: sticky bit has come loose",
  "#439: Hot Java has gone cold",
  "#440: Cache miss - please take better aim next time",
  "#441: Hash table has woodworm",
  "#442: Trojan horse ran out of hay",
  "#443: Zombie processes detected, machine is haunted.",
  "#444: overflow error in /dev/null",
  "#445: Browser's cookie is corrupted -- someone's been nibbling on it",
  "#446: Mailer-daemon is busy burning your message in hell.",
  "#447: According to Microsoft, it's by design",
  "#448: vi needs to be upgraded to vii",
  "#449: greenpeace free'd the mallocs",
  "#450: Terrorists crashed an airplane into the server room, have to remove /bin/laden. (rm -rf /bin/laden)",
  "#451: astropneumatic oscillations in the water-cooling",
  "#452: Somebody ran the operating system through a spelling checker",
  "#453: Spider infestation in warm case parts"};

#endif
